const data = [
    {
        id: '1',
        title: 'Convert a jQuery library to React',
        skills: ['Redesign an application to reduce technical debt', 'Analyze the performance of a web app', 'Unit testing'],
        technologies: ['React', 'React Router', 'Redux / Toolkit', 'Emotion', 'Jest', 'Testing-Library'],
        url: 'https://www.npmjs.com/package/basic-react-dropdown',
        img: 'hrnet.png',
    },
    {
        id: '2',
        title: 'Use an API for a bank user account with React',
        skills: ['Implement a state manager in a React application using Redux / Toolkit', 'Interact with an API', 'Authentication with an API'],
        technologies: ['React', 'React Router', 'Redux / Toolkit', 'Axios'],
        url: 'https://github.com/AmandaSrisourath/ArgentBank',
        img: 'argentBank.png',
    },
    {
        id: '3',
        title: 'Build an analytics dashboard with React',
        skills: ['Interact with a web service', 'Develop advanced graphical elements using recharts', 'Produce technical documentation for an application'],
        technologies: ['React', 'React Router', 'Axios', 'Recharts'],
        url: 'https://github.com/AmandaSrisourath/SportSee',
        img: 'sportSee.png',
    },
    {
        id: '4',
        title: 'Create an app with React and React Router',
        skills: ['Developing routes for a web application with React Router', 'Initialize a web application with a framework', 'Create components with React'],
        technologies: ['React', 'React Router', 'Figma'],
        url: 'https://amandasrisourath.github.io/Kasa/#/',
        img: 'kasa.png',
    },
    {
        id: '5',
        title: 'Define the needs for a tutoring app',
        skills: ['Create mockups for a client with Figma', 'Contribute to a project using an agile methodology', 'Identify the needs of the application from a specification', 'Model a technical solution for a client'],
        technologies: ['Figma', 'Trello'],
        url: 'https://www.figma.com/file/a9JwLOrCBB4HPMg0dZYJn1/Learn%40Home',
        img: 'learn@Home.png',
    },
    {
        id: '6',
        title: 'Create an accessible website',
        skills: ['Manage site events with JavaScript', 'Develop a modular web application with design patterns', 'Write maintainable JavaScript code', 'Ensuring the accessibility of a website'],
        technologies: ['HTML5', 'CSS3','SASS', 'JavaScript'],
        url: 'https://amandasrisourath.github.io/FishEye/',
        img: 'fishEye.png',
    },
    {
        id: '7',
        title: 'Create a landing page with Javascript',
        skills: ['Programming in JavaScript'],
        technologies: ['HTML5', 'CSS3', 'JavaScript'],
        url: 'https://amandasrisourath.github.io/GameOn/',
        img: 'gameOn.png',
    },
    {
        id: '8',
        title: 'Make a dynamic page with CSS animations',
        skills: ['Ensuring the graphic consistency of a website', 'Use a version control system for project tracking and hosting', 'Implementing advanced graphic CSS effects', 'Setting up the Front-End environment'],
        technologies: ['HTML5', 'CSS3', 'Figma'],
        url: 'https://amandasrisourath.github.io/OhMyFood/',
        img: 'ohMyFood.png',
    },
    {
        id: '9',
        title: 'Create a website with HTML5 and CSS3',
        skills: ['Implement a responsive interface', 'Integrate content according to mockups'],
        technologies: ['HTML5', 'CSS3', 'Figma'],
        url: 'https://amandasrisourath.github.io/Reservia/',
        img: 'reservia.png',
    },
]

export { data };